-- MySQL Script generated by MySQL Workbench
-- Mon May  8 10:15:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema infofit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infofit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infofit` DEFAULT CHARACTER SET utf8 ;
USE `infofit` ;

-- -----------------------------------------------------
-- Table `infofit`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infofit`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `gender` ENUM("Male", "Female") NOT NULL,
  `birthdate` DATE NOT NULL,
  `height` SMALLINT(3) UNSIGNED NOT NULL,
  `weight` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Uniqueuser` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infofit`.`foodstuffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infofit`.`foodstuffs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `kcal_100g` SMALLINT(4) UNSIGNED NOT NULL,
  `carbohydrates_100g` SMALLINT(4) UNSIGNED NOT NULL,
  `lipids_100g` SMALLINT(4) UNSIGNED NOT NULL,
  `proteins_100g` SMALLINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Uniquefoodstuff` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infofit`.`users_has_foodstuffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infofit`.`users_has_foodstuffs` (
  `id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `foodstuffs_id` INT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `quantity` SMALLINT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_foodstuffs_foodstuffs1_idx` (`foodstuffs_id` ASC) VISIBLE,
  INDEX `fk_users_has_foodstuffs_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_foodstuffs_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `infofit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_foodstuffs_foodstuffs1`
    FOREIGN KEY (`foodstuffs_id`)
    REFERENCES `infofit`.`foodstuffs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
